/**
 * Indentation-preserving XML serializer.
 *
 * @xmldom/xmldom's built-in XMLSerializer produces a single flat line.
 * This module provides a pretty-printer that re-serializes a DOM Document
 * with consistent indentation.
 */
import type { Document, Element, Node } from '@xmldom/xmldom';
import { ELEMENT_NODE, TEXT_NODE, COMMENT_NODE } from './xmlUtils.js';

const CDATA_NODE = 4;
const PROCESSING_INSTRUCTION_NODE = 7;
const ATTRIBUTE_NODE = 2;

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Serializes a DOM Document to a well-formatted XML string.
 *
 * @param doc        The document to serialize.
 * @param indentSize Number of spaces per indent level.
 * @param newLine    Line ending to use (default '\n').
 */
export function serializeDocument(
  doc: Document,
  indentSize: number,
  newLine = '\n'
): string {
  const indentUnit = ' '.repeat(Math.max(1, indentSize));
  const lines: string[] = [];

  // XML declaration
  const version = (doc as unknown as { xmlVersion?: string }).xmlVersion ?? '1.0';
  const encoding = (doc as unknown as { xmlEncoding?: string }).xmlEncoding ?? 'utf-8';
  lines.push(`<?xml version="${version}" encoding="${encoding}"?>`);

  if (doc.documentElement) {
    serializeNode(doc.documentElement, 0, indentUnit, lines);
  }

  return lines.join(newLine) + newLine;
}

// ─── Node serialization ───────────────────────────────────────────────────────

function serializeNode(
  node: Node,
  depth: number,
  indentUnit: string,
  lines: string[]
): void {
  switch (node.nodeType) {
    case ELEMENT_NODE:
      serializeElement(node as Element, depth, indentUnit, lines);
      break;
    case COMMENT_NODE: {
      const data = (node as unknown as { data?: string }).data ?? node.nodeValue ?? '';
      lines.push(`${indentUnit.repeat(depth)}<!--${data}-->`);
      break;
    }
    case PROCESSING_INSTRUCTION_NODE: {
      const pi = node as unknown as { target?: string; data?: string };
      lines.push(`${indentUnit.repeat(depth)}<?${pi.target ?? ''} ${pi.data ?? ''}?>`);
      break;
    }
    default:
      break;
  }
}

function serializeElement(
  elem: Element,
  depth: number,
  indentUnit: string,
  lines: string[]
): void {
  const indentStr = indentUnit.repeat(depth);
  const tagName = elem.tagName ?? elem.localName;
  const attrs = buildAttributeString(elem);

  // Classify children
  let hasElementOrCommentChildren = false;
  let textContent = '';
  let hasMixedContent = false;
  let nonWsTextCount = 0;

  let child = elem.firstChild;
  while (child) {
    if (child.nodeType === ELEMENT_NODE || child.nodeType === COMMENT_NODE) {
      hasElementOrCommentChildren = true;
    } else if (child.nodeType === TEXT_NODE) {
      const raw = (child as unknown as { data?: string }).data ?? child.nodeValue ?? '';
      const trimmed = raw.trim();
      if (trimmed) {
        nonWsTextCount++;
        textContent += trimmed;
        if (hasElementOrCommentChildren) {
          hasMixedContent = true;
        }
      }
    } else if (child.nodeType === CDATA_NODE) {
      textContent += (child as unknown as { data?: string }).data ?? child.nodeValue ?? '';
      nonWsTextCount++;
      if (hasElementOrCommentChildren) {
        hasMixedContent = true;
      }
    }
    child = child.nextSibling;
  }

  const hasText = nonWsTextCount > 0;
  const hasBlockChildren = hasElementOrCommentChildren;

  if (!hasText && !hasBlockChildren) {
    // Empty element
    lines.push(`${indentStr}<${tagName}${attrs}/>`);
    return;
  }

  if (hasText && !hasBlockChildren) {
    // Pure text content — inline
    lines.push(`${indentStr}<${tagName}${attrs}>${escapeText(textContent)}</${tagName}>`);
    return;
  }

  if (hasMixedContent) {
    // Mixed: just inline everything (rare in X4 XML)
    lines.push(`${indentStr}<${tagName}${attrs}>${collectInlineContent(elem)}</${tagName}>`);
    return;
  }

  // Element/comment content with possible whitespace-only text nodes
  lines.push(`${indentStr}<${tagName}${attrs}>`);
  child = elem.firstChild;
  while (child) {
    if (child.nodeType === ELEMENT_NODE || child.nodeType === COMMENT_NODE) {
      serializeNode(child, depth + 1, indentUnit, lines);
    } else if (child.nodeType === TEXT_NODE) {
      const raw = (child as unknown as { data?: string }).data ?? child.nodeValue ?? '';
      const trimmed = raw.trim();
      if (trimmed) {
        // Non-whitespace text inside element-bearing parent — treat as block
        lines.push(`${indentUnit.repeat(depth + 1)}${escapeText(trimmed)}`);
      }
      // Whitespace-only text nodes are dropped (regenerated by indentation)
    }
    child = child.nextSibling;
  }
  lines.push(`${indentStr}</${tagName}>`);
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function buildAttributeString(elem: Element): string {
  if (!elem.attributes || elem.attributes.length === 0) {
    return '';
  }
  let s = '';
  for (let i = 0; i < elem.attributes.length; i++) {
    const a = elem.attributes[i];
    s += ` ${a.name}="${escapeAttr(a.value)}"`;
  }
  return s;
}

function collectInlineContent(elem: Element): string {
  let s = '';
  let child = elem.firstChild;
  while (child) {
    if (child.nodeType === ELEMENT_NODE) {
      const e = child as Element;
      const tag = e.tagName ?? e.localName;
      const attrs = buildAttributeString(e);
      const inner = collectInlineContent(e);
      s += inner ? `<${tag}${attrs}>${inner}</${tag}>` : `<${tag}${attrs}/>`;
    } else if (child.nodeType === TEXT_NODE) {
      const raw = (child as unknown as { data?: string }).data ?? child.nodeValue ?? '';
      s += escapeText(raw);
    } else if (child.nodeType === COMMENT_NODE) {
      const data = (child as unknown as { data?: string }).data ?? child.nodeValue ?? '';
      s += `<!--${data}-->`;
    }
    child = child.nextSibling;
  }
  return s;
}

function escapeText(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

function escapeAttr(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
